### ISSUE TITLE
弄了两天弄不懂，求助，如图

### ISSUE THREAD

**Issue by scyraxs** [yjqiang/geetest_test#1]
python3.8.1 win10 
文件均为2020.1.11更新
![run py2020-01-11_153109](https://user-images.githubusercontent.com/49806577/72200689-6f414800-3487-11ea-9bcc-da4a84a0bd50.png)
![server py2020-01-11_152802](https://user-images.githubusercontent.com/49806577/72200693-76685600-3487-11ea-8d17-4c75ba7b783b.png)
![client py2020-01-11_152818](https://user-images.githubusercontent.com/49806577/72200696-78321980-3487-11ea-9538-f52d170e8681.png)

**Comment by yjqiang** [comment]
这个只是一个demo罢了，和 bili2.0 的对接并没有完成。
其实主站已经开始点字验证码了，可能我会不久考虑其他办法，这个东西算是一个学习记录吧。

**Comment by yjqiang** [comment]
刚刚提交了一个修改在bili2.0，如果你不是专门研究验证码，可以忽略这个项目了
